Hash-based package routes
quiltdata/quilt pull request #1938
Opened 2020-11-26 14:50 UTC by nl0

# Description

Use top_hash in package routes, completely remove timestamps from the UI (timestamp revisions are still resolved, so it's backwards compatible).

# TODO

- [ ] [Changelog](CHANGELOG.md) entry

2020-11-26 15:20 UTC, fiskus reviewed
I will do manual tests tomorrow

2020-11-26 15:20 UTC, fiskus commented on catalog/app/utils/search.js
> +    // eslint-disable-next-line no-console
Please, review https://github.com/quiltdata/quilt/pull/1882

2020-11-26 15:20 UTC, fiskus commented on catalog/app/components/SearchResults/SearchResults.js
> +          {R.take(10, hash)}
Such things as `10` over the code are more maintainable as constants in one place. Much better if we would have some function that responsible for `hash => R.take(10, hash)`. In such a case, we would have a single implementation, that could be changed in one place.

2020-11-27 05:56 UTC, nl0 commented on catalog/app/utils/search.js
> +    // eslint-disable-next-line no-console
i will

2020-11-27 06:37 UTC, fiskus commented
Old URL works /b/fiskus-sandbox-dev/packages/fiskus/2011-11-16/tree/1605546363/
I don't know if this technically doable, we can make 301 redirect to new URL b/fiskus-sandbox-dev/packages/fiskus/2011-11-16/tree/67c766d5108b4dc2a7c3b74c8fd9287d880829158603de77bebf73288a7fdc81/

Also, I recall that we talked about short hashes (a la GitHub https://github.com/quiltdata/quilt/pull/1938/commits/d5a76a3), but I don't remember what we decide

2020-11-27 06:47 UTC, nl0 commented
> I don't know if this technically doable, we can make 301 redirect to new URL

not possible until we implement server-side rendering, tho we can redirect to the more "canonical" hash-based route on the front-end.

@akarve do we want to redirect to the new routes?

> Also, I recall that we talked about short hashes (a la GitHub d5a76a3), but I don't remember what we decide

this will require backend support, so i think we should add this feature later (along with tags support)

2020-11-27 06:53 UTC, fiskus approved these changes
Didn't spot any bugs, except for inconsistency with old timestamps (not a bug, intentional)

![Screenshot from 2020-11-27 09-51-44](https://user-images.githubusercontent.com/533229/100419826-5d17ca80-3096-11eb-963f-b3e97231f216.png)

2020-11-30 03:29 UTC, akarve approved these changes
Mostly works in testing. See a few notes in Slack.

2020-11-30 03:29 UTC, akarve commented on docs/CHANGELOG.md
> +* [Changed] `top_hash`-based package routes (backwards compatible) ([#1938](https://github.com/quiltdata/quilt/pull/1938))
This is reasonable behavior but I'm wondering if forwarding to a dedicated `/h/` or whatever hash route is more correct in terms of traceability? Please make a note that /timestamp URLs are not forwarded in any way, but that the user remains at /timestamp.

2020-11-30 03:43 UTC, akarve requested changes
See potential bugs in Slack?

2020-11-30 03:46 UTC, akarve commented on docs/CHANGELOG.md
> +* [Changed] `top_hash`-based package routes (backwards compatible) ([#1938](https://github.com/quiltdata/quilt/pull/1938))
To be clear I am totally cool with current behavior (honor both types of routes, no redirect). I am just asking if anything becomes cleaner or safer with two routes.

2020-11-30 03:52 UTC, akarve approved these changes

2020-11-30 05:59 UTC, merged