support for list of paths to fetch for one file
quiltdata/quilt pull request #2118
Opened 2021-03-19 17:17 UTC by fiskus

2021-03-20 05:59 UTC, nl0 requested changes
the implementation seems counter-intuitive for couple of reasons:
- only the first and the last items of the list are tried, other items possibly existing in the middle are ignored
- last item is tried first, which doesnt make sense to me

proposition: iterate thru the list from start and return the first positive result

2021-03-20 06:00 UTC, nl0 commented on catalog/app/containers/Bucket/requests.js
> +  const isPresent = Array.isArray(path)
we could just normalize path (convert it to a list) and use `ensureObjectIsPresentInCollection`

2021-03-22 06:15 UTC, fiskus commented
> only the first and the last items of the list are tried, other items possibly existing in the middle are ignored

You probably confused `R.init` with `R.head`. `R.head` returns first element of array, but `R.init` returns _array_ without last element.

I double-checked: all items on the list are tried

2021-03-22 06:56 UTC, nl0 commented
> > only the first and the last items of the list are tried, other items possibly existing in the middle are ignored
> 
> You probably confused `R.init` with `R.head`. `R.head` returns first element of array, but `R.init` returns _array_ without last element.
> 
> I double-checked: all items on the list are tried

yeah i see now, but still i think it's more logical to use the natural order (try the first item of the array first)

2021-03-22 06:58 UTC, fiskus commented
I turned the list of file paths over

2021-03-22 07:01 UTC, nl0 approved these changes

2021-03-22 07:01 UTC, nl0 commented on catalog/app/containers/Bucket/requests.js
> +    key: R.head(keys),
`keys[0]`? =)

2021-03-23 06:06 UTC, merged