Vega fallback loader
quiltdata/quilt pull request #2248
Opened 2021-07-05 13:01 UTC by fiskus

If a request with "Range: bytes" fails then request full file contents.

2021-07-05 15:31 UTC, nl0 reviewed
seems like this code will try to load the whole file regardless of its size, and i'm afraid this can be a problem for like 10MB+ files

2021-07-05 15:31 UTC, nl0 commented on catalog/app/components/Preview/loaders/Json.js
> +        sentry('captureException', error)
did you mean this?
```suggestion
        sentry('captureException', err)
```

2021-07-06 07:28 UTC, fiskus commented
I added HEAD request to check the file's size

2021-07-06 16:05 UTC, fiskus commented
We discussed and decided to move head request BEFORE bytes request, because it makes more sense to make a correct request instead of making an error request and do something to fix it after.

2021-07-06 16:06 UTC, nl0 requested changes
as per zoom discussion: we should use head request before scanning the first bytes

2021-07-07 08:25 UTC, fiskus commented
I moved `HEAD` request before `Range: bytes` request

2021-07-07 13:41 UTC, nl0 approved these changes

2021-07-07 13:48 UTC, merged