Update @testing-library and jest dependencies
quiltdata/quilt pull request #2250
Opened 2021-07-05 18:21 UTC by fiskus

2021-07-05 18:26 UTC, fiskus commented on catalog/app/components/Dropzone/Dropzone.spec.js
> + * @jest-environment jsdom
https://github.com/facebook/jest/pull/9874/files

https://jestjs.io/docs/configuration#testenvironment-string

2021-07-06 06:41 UTC, nl0 requested changes
i think we should set jest-environment globally. plus i've noticed some unrelated stuff in package.json diff -- is that intentional?

2021-07-06 06:41 UTC, nl0 commented on catalog/package.json
> +    "@typescript-eslint/parser": "^4.28.2",
some leftover stuff from the previous pr?

2021-07-06 06:41 UTC, nl0 commented on catalog/app/containers/Bucket/viewModes.spec.ts
> + * @jest-environment jsdom
i think we should set this globally in `jest.config.js`, since we're testing a web app and targeting browser-like environment

2021-07-06 06:58 UTC, nl0 approved these changes

2021-07-06 07:22 UTC, merged