Un-stick pylint version, and disable new rules inline
quiltdata/quilt pull request #2318
Opened 2021-08-25 12:42 UTC by fiskus

2021-08-25 12:59 UTC, nl0 approved these changes

2021-09-01 12:08 UTC, fiskus commented
@sir-sigurd can you check this? For some reason code coverage shows an error

---

Some background: pylint showed warning after update; I stuck version to last compatible; then in this PR I un-stuck pylint version and hide warnings instead

2021-09-01 17:01 UTC, sir-sigurd requested changes
I think that we should specify encoding instead of ignoring this linter rule. We already had a [bug](https://github.com/quiltdata/quilt/issues/1929) that affected users. In some cases we might want to use ASCII and use UTF-8 in others, so I'll take other this PR.

2021-09-20 18:32 UTC, fiskus commented
> I think that we should specify encoding instead of ignoring this linter rule

Sure, but I won't do this. If you don't want to temporarily ignore warnings and un-stick pylint version, I'm going to close this PR

2021-09-21 17:32 UTC, merged