Add docs section on running quilt3 in Databricks
quiltdata/quilt pull request #2736
Opened 2022-03-12 14:51 UTC by kevinemoore

# Description

Adding a docs section under Advanced on running Quilt in Databricks. The first topic is how to install quilt3 on a Databricks cluster. Future topics might include:
* S3 permissions
* packaging parquet files

# TODO

<del>
- [ ] Unit tests
- [ ] Automated tests (e.g. Preflight)
- [ ] Documentation
    - [ ] [Python: Run `build.py`](../gendocs/build.py) for new docstrings
    - [ ] JavaScript: basic explanation and screenshot of new features
- [ ] [Changelog](CHANGELOG.md) entry
</del>

2022-03-22 01:25 UTC, akarve requested changes

2022-03-22 01:25 UTC, akarve commented on docs/SUMMARY.md
> +* [Running Quilt in Databricks](databricks.md)
```suggestion
* [Databricks](databricks.md)
```

2022-03-22 01:25 UTC, akarve commented on docs/databricks.md
> +Before using `quilt3` in your Databricks notebooks, you'll need to install it on your cluster. Find your cluster from the __Compute__ tab. From your Cluster overview, click on the __Libraries__ tab,
Please add a paragraph with more setup on why people would use Quilt with Databricks, how functions complement, Quilt is compute agnostic, etc.

2023-03-07 19:38 UTC, akarve approved these changes

2024-12-24 17:48 UTC, drernie commented
@kevinemoore Closing, unless you want to re-open and push through.

2024-12-24 17:48 UTC, closed without merging