Docs for selective metadata UI preferences
quiltdata/quilt pull request #2942
Opened 2022-07-19 09:37 UTC by fiskus

Feature PR: https://github.com/quiltdata/quilt/pull/2941

2022-07-23 02:19 UTC, akarve requested changes

2022-07-23 02:19 UTC, akarve commented on docs/Catalog/Preferences.md
> +  * tagA
Sorry to change the key name but `.packages` is too broad. I realize we will need other JS changes to accommodate.
```suggestion
* `ui.package_description` - a dictionary that maps package handle regular expressions or literals to JSONPath expressions of fields to show from package metadata in the package list view.
The key `*` matches all packages. Strings display as paragraphs. Elements of a list display as tags.

#### `ui.package_description` example
  
```

2022-07-23 02:19 UTC, akarve commented on docs/Catalog/Preferences.md
> +        - $.key4[0]
```suggestion
ui:
  packages:
    # match all packages
    *:
      # show the message
      message: True
      # show the .labels field
      user_meta:
        - $.labels
    # for any package with a handle prefix of foo
    foo/*:
      # JSONPath expressions to the fields to display
      user_meta:
        - $.key1.key2
        - $.key3
        - $.key4[0]
```

2022-07-23 02:19 UTC, akarve commented on docs/Catalog/Preferences.md
> +        - $.key4[0]
tagA is very confusing below because it's not a tag :)

2022-07-28 04:02 UTC, nl0 approved these changes

2022-07-28 16:37 UTC, akarve approved these changes

2022-07-28 16:46 UTC, merged