Explain drawbacks of physical folders vs logical packages
quiltdata/quilt pull request #2954
Opened 2022-07-27 22:32 UTC by akarve

# Description

# TODO

- [n/a] Unit tests
- [n/a] Automated tests (e.g. Preflight)
- [x] Documentation
    - [n/a] [Python: Run `build.py`](../gendocs/build.py) for new docstrings
    - [n/a] JavaScript: basic explanation and screenshot of new features
- [n/a] [Changelog](CHANGELOG.md) entry

2022-07-28 00:10 UTC, drernie reviewed
Looks good. One question:
> Or you can "reorganize" S3, without moving any objects
Is there is a better phrase than "reorganize S3" - which to me implys "moving objects around"

Is this about 'reorganizing packages' without modifying S3?

2022-07-28 00:12 UTC, drernie requested changes
> everything that happened on a given *data*
everything that happened on a given date

2022-07-29 18:52 UTC, akarve commented on docs/advanced-features/s3-bucket-organization.md
> +look at everything that happened on a given data. And vice versa. Since
```suggestion
look at everything that happened on a given date. And vice versa. Since
```

2022-07-29 19:06 UTC, akarve commented on docs/advanced-features/s3-bucket-organization.md
>  by using Quilt packages and the `.set*()` API calls.
```suggestion
With Quilt packages, you can include a given S3 object in as many
packages without ever copying that object. Or you can organize multiple S3 buckets
into single packages under any logical folder structure that you wish (by using the Quilt catalog
or `.set*()` APIs).
```

2022-07-29 19:22 UTC, drernie approved these changes
Looks good!

2022-08-05 23:31 UTC, drernie commented
@akarve Are you awaiting something from me before merging?

2022-08-16 04:54 UTC, merged