Add single quotes around pip install command
quiltdata/quilt pull request #3283
Opened 2023-01-19 21:11 UTC by robnewman

# Description
Fix all references to `pip install 'quilt3[catalog]'`

# TODO

- [n/a] Unit tests
- [n/a] Automated tests (e.g. Preflight)
- [X] Documentation
    - [n/a] [Python: Run `build.py`](../gendocs/build.py) for new docstrings
    - [n/a] JavaScript: basic explanation and screenshot of new features
- [n/a] [Changelog](CHANGELOG.md) entry (skip if change is not significant to end users, e.g. docs only)

2023-01-19 21:30 UTC, akarve commented on docs/CHANGELOG.md
> +* [Changed] `quilt3 catalog` now requires `quilt3` to be installed with `catalog` extra dependency (`pip install 'quilt3[catalog]'`).
No changelog for docs changes, right?

2023-01-19 21:30 UTC, akarve commented on docs/CHANGELOG.md
> +* [Changed] `quilt3 catalog` now requires `quilt3` to be installed with `catalog` extra dependency (`pip install 'quilt3[catalog]'`).
Description is also incorrect. We just need to single quote any instances of the extras installs.

2023-01-19 21:34 UTC, akarve submitted a review, later dismissed
Need more quotes e.g. here https://docs.quiltdata.com/installation#python-client

2023-01-20 06:13 UTC, sir-sigurd commented
Also https://github.com/quiltdata/quilt/blob/0f50ca57edc95e1bd795c28c90de44b3d0146cf9/docs/CONTRIBUTING.md?plain=1#L37.

2023-01-20 06:13 UTC, sir-sigurd requested changes
https://github.com/quiltdata/quilt/blob/0f50ca57edc95e1bd795c28c90de44b3d0146cf9/docs/CONTRIBUTING.md?plain=1#L37

2023-01-23 14:37 UTC, sir-sigurd approved these changes
I'd prefer line wrapping changes done separately, but OK.

2023-02-03 16:56 UTC, merged