Athena docs: add screenshots and mention `physical_key` and `defaultWorkgroup`
quiltdata/quilt pull request #4217
Opened 2024-11-15 11:51 UTC by fiskus

2024-11-15 17:06 UTC, drernie requested changes

2024-11-15 17:06 UTC, drernie commented on docs/Catalog/SearchQuery.md
> +It is also possible to set default workgroup in `ui > athena > defaultWorkgroup: 'you-default-workgroup'`.
```suggestion
It is also possible to set the default workgroup in `ui > athena > defaultWorkgroup: 'your-default-workgroup'`.
```
Lost the 'r'

2024-11-15 17:06 UTC, drernie commented on docs/Catalog/SearchQuery.md
> +Workgroup, catalog name and database selects memorize the last selected value.
```suggestion
The tab will remember the last workgroup, catalog name and database that was selected.
```

2024-11-15 19:56 UTC, drernie approved these changes

2024-11-18 10:17 UTC, fiskus commented on docs/Catalog/SearchQuery.md
> +([Learn more](./Preferences.md)).
```suggestion
[Learn more](./Preferences.md).
```

2024-11-18 16:17 UTC, merged